using ClaimsCaseManagement.Data;
using ClaimsCaseManagement.Models;
using Microsoft.EntityFrameworkCore;

namespace ClaimsCaseManagement.Services;

// Legacy smell: a single "god service" responsible for validation,
// persistence, status-workflow rules, notifications, and reporting.
// Every controller depends on this class directly, and it depends
// directly on the DbContext and NotificationService - no layering,
// no domain events, no separation between commands and queries.
public class ClaimService : IClaimService
{
    private readonly ClaimsDbContext _context;
    private readonly INotificationService _notificationService;
    private readonly ILogger<ClaimService> _logger;

    public ClaimService(ClaimsDbContext context, INotificationService notificationService, ILogger<ClaimService> logger)
    {
        _context = context;
        _notificationService = notificationService;
        _logger = logger;
    }

    public async Task<Claim> CreateClaimAsync(Claim claim)
    {
        // Validation logic lives here rather than in the domain model or a validator.
        if (claim.EstimatedAmount <= 0)
        {
            throw new InvalidOperationException("Estimated amount must be greater than zero.");
        }

        claim.ClaimNumber = await GenerateClaimNumberAsync();
        claim.DateSubmitted = DateTime.UtcNow;
        claim.Status = ClaimStatus.Submitted;

        _context.Claims.Add(claim);
        await _context.SaveChangesAsync();

        // Reload with navigation properties for the notification (relies on lazy loading proxies).
        var saved = await _context.Claims
            .Include(c => c.Claimant)
            .Include(c => c.Policy)
            .FirstAsync(c => c.ClaimId == claim.ClaimId);

        await _notificationService.SendClaimSubmittedEmailAsync(saved);

        _context.ClaimStatusHistories.Add(new ClaimStatusHistory
        {
            ClaimId = saved.ClaimId,
            OldStatus = ClaimStatus.Submitted,
            NewStatus = ClaimStatus.Submitted,
            ChangedBy = "system",
            Comment = "Claim submitted."
        });
        await _context.SaveChangesAsync();

        return saved;
    }

    public async Task ChangeStatusAsync(int claimId, ClaimStatus newStatus, string changedBy, string? comment)
    {
        var claim = await _context.Claims
            .Include(c => c.Claimant)
            .Include(c => c.Policy)
            .FirstOrDefaultAsync(c => c.ClaimId == claimId);

        if (claim is null)
        {
            throw new InvalidOperationException($"Claim {claimId} not found.");
        }

        var oldStatus = claim.Status;

        // Status-transition rules hardcoded inline rather than expressed as a
        // workflow/state machine - hard to test and easy to bypass.
        if (oldStatus == ClaimStatus.Closed)
        {
            throw new InvalidOperationException("Cannot change status of a closed claim.");
        }

        if (newStatus == ClaimStatus.Approved && claim.ApprovedAmount is null)
        {
            claim.ApprovedAmount = claim.EstimatedAmount;
        }

        claim.Status = newStatus;
        _context.ClaimStatusHistories.Add(new ClaimStatusHistory
        {
            ClaimId = claim.ClaimId,
            OldStatus = oldStatus,
            NewStatus = newStatus,
            ChangedBy = changedBy,
            Comment = comment
        });

        await _context.SaveChangesAsync();
        await _notificationService.SendStatusChangedEmailAsync(claim, oldStatus, newStatus);
    }

    public async Task<IEnumerable<Claim>> GetOpenClaimsForAdjusterAsync(int adjusterId)
    {
        return await _context.Claims
            .Where(c => c.AdjusterId == adjusterId && c.Status != ClaimStatus.Closed && c.Status != ClaimStatus.Denied)
            .Include(c => c.Claimant)
            .Include(c => c.Policy)
            .ToListAsync();
    }

    public async Task<ClaimSummaryReport> GetSummaryReportAsync()
    {
        // Reporting/analytics logic embedded in the same service as transactional
        // operations - no separate read model or reporting store.
        var claims = await _context.Claims.ToListAsync();

        var total = claims.Count;
        var open = claims.Count(c => c.Status != ClaimStatus.Closed && c.Status != ClaimStatus.Denied);
        var exposure = claims.Where(c => c.Status != ClaimStatus.Denied).Sum(c => c.EstimatedAmount);
        var approved = claims.Where(c => c.ApprovedAmount.HasValue).Sum(c => c.ApprovedAmount!.Value);

        return new ClaimSummaryReport(total, open, exposure, approved);
    }

    private async Task<string> GenerateClaimNumberAsync()
    {
        // Legacy smell: claim number generated by counting rows - not
        // concurrency-safe and will collide under load.
        var count = await _context.Claims.CountAsync();
        return $"CLM-{100000 + count + 1}";
    }
}
